### PR TITLE
Fork and Link TGGE Repo to Plugins

### PR DESCRIPTION
**Pull request by MerlinStWahgwaan**

### CODE REVIEW

**Comment by MerlinStWahgwaan** [comment]
OOPS, ignore me, worng thing, sorry

**Comment by MerlinStWahgwaan** [comment]
i still dont know why this keeps happening when i try to pull and merge, sorry

**Comment by MerlinStWahgwaan** [comment]
close req

**Comment by MerlinStWahgwaan** [comment]
close req

**Comment by MerlinStWahgwaan** [comment]
close req

**Comment by MerlinStWahgwaan** [comment]
i dont seem able to close this req and i dont know why

**Comment by MerlinStWahgwaan** [comment]
xlose

**Comment by budak7273** [comment]
You should be able to close this yourself with the button next to the comment button.

**Comment by MerlinStWahgwaan** [comment]
APOLOGIES.... wont use fork again until/unless i learn git, so as not to create these by accident.

**Comment by MerlinStWahgwaan** [comment]
sooo.... close pull request button,.. seems to post my comment, but not close the request... -_-" lord what have i done

**Pull request closed without merging**
